/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.55
 * Generated at: 2022-02-10 01:11:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/Users/Onion/Desktop/TIL/SmallProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/BookStore/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1644412687300L));
    _jspx_dependants.put("/member/../header.jsp", Long.valueOf(1644412687305L));
    _jspx_dependants.put("jar:file:/C:/Users/Onion/Desktop/TIL/SmallProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/BookStore/WEB-INF/lib/standard.jar!/META-INF/fmt.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/member/../footer.jsp", Long.valueOf(1644412687304L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>BookStore</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/book.css\">\r\n");
      out.write("<script src=\"script/jquery-3.6.0.js\"></script>\r\n");
      out.write("<script src=\"css/test.js\"></script>\r\n");
      out.write("<script src=\"member/member.js\"></script>\r\n");
      out.write("<script src=\"mypage/mypage.js\"></script>\r\n");
      out.write("<script src=\"main.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"wrap\">\r\n");
      out.write("	<header>\r\n");
      out.write("		<div>\r\n");
      out.write("			<nav id=\"top_menu\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><a href=\"bs.do?cmd=qna\" style=\"border:0px;\">고객센터</a></li>\r\n");
      out.write("					<li><a href=\"bs.do?cmd=orderView\" style=\"width:80px;\">주문/배송조회</a></li>\r\n");
      out.write("					<li><a href=\"bs.do?cmd=cart\">장바구니</a></li>\r\n");
      out.write("					<li><a href=\"bs.do?cmd=joinForm\">회원가입</a></li>\r\n");
      out.write("					<li><a href=\"bs.do?cmd=loginForm\">로그인</a></li>\r\n");
      out.write("					<li><a href=\"bs.do?cmd=mypage\">마이페이지</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</nav>\r\n");
      out.write("		</div>\r\n");
      out.write("		<br><br>\r\n");
      out.write("		\r\n");
      out.write("		<!-- 검색창 -->\r\n");
      out.write("		<div id=\"top\">\r\n");
      out.write("			<div id=\"logo\">\r\n");
      out.write("				<a href=\"bs.do?cmd=index\"><img alt=\"\" src=\"images/main/logo.png\"></a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div id=\"search\">\r\n");
      out.write("			<!--\r\n");
      out.write("				<div id=\"drop\">\r\n");
      out.write("					<a href=\"#\" class=\"dbutton\">통합검색</a>\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"#\">통합검색</a></li>\r\n");
      out.write("						<li><a href=\"#\">국내도서</a></li>\r\n");
      out.write("						<li><a href=\"#\">외국도서</a></li>\r\n");
      out.write("						<li><a href=\"#\">리뷰</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>  -->\r\n");
      out.write("				\r\n");
      out.write("				<!-- \r\n");
      out.write("				<div class=\"dropdown\">\r\n");
      out.write("			      <span class=\"dropbtn\">drop down</span>\r\n");
      out.write("			      <div class=\"dropdown-content\">\r\n");
      out.write("			        <a href=\"#\">link 1</a>\r\n");
      out.write("			        <a href=\"#\">link 2</a>\r\n");
      out.write("			        <a href=\"#\">link 3</a>\r\n");
      out.write("			      </div>\r\n");
      out.write("			    </div>\r\n");
      out.write("			     -->\r\n");
      out.write("			     \r\n");
      out.write("			    <div class=\"day_box\">\r\n");
      out.write("					<select id=\"day_font\">\r\n");
      out.write("					   <option>통합검색</option>\r\n");
      out.write("					   <option>국내도서</option>\r\n");
      out.write("					   <option>외국도서</option>\r\n");
      out.write("					   <option>리뷰</option>\r\n");
      out.write("					</select>\r\n");
      out.write("					<input type=\"text\" id=\"searchbox\" placeholder=\"검색어입력\"/>\r\n");
      out.write("					<input type=\"button\" id=\"button1\" onClick=\"\"/>\r\n");
      out.write("				</div>	\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<br><br>\r\n");
      out.write("		\r\n");
      out.write("		<div>\r\n");
      out.write("			<nav id=\"index_menu\">\r\n");
      out.write("				<ul class=\"menu\">\r\n");
      out.write("					<li><a href=\"bs.do?cmd=menu&kind=1\">베스트도서</a></li>\r\n");
      out.write("					<li><a href=\"bs.do?cmd=menu&kind=2\">신간도서</a></li>\r\n");
      out.write("					<li><a href=\"bs.do?cmd=menu&kind=3\">국내도서</a></li>\r\n");
      out.write("					<li><a href=\"bs.do?cmd=menu&kind=4\">외국도서</a></li>\r\n");
      out.write("					<li><a href=\"bs.do?cmd=menu&kind=5\">이벤트</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</nav>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- </div> -->");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<article>\r\n");
      out.write("<h1>Login</h1>\r\n");
      out.write("<form method=\"post\" action=\"bs.do\" name=\"loginFrm\">\r\n");
      out.write("	<input type=\"hidden\" name=\"cmd\" value=\"login\">\r\n");
      out.write("	\r\n");
      out.write("	<fieldset>\r\n");
      out.write("		<legend></legend>\r\n");
      out.write("			<label>User ID</label><input name=\"id\" type=\"text\"><br> \r\n");
      out.write("	        <label>Password</label><input name=\"pwd\" type=\"password\"><br>\r\n");
      out.write("	</fieldset>\r\n");
      out.write("	<div id=\"buttons\">\r\n");
      out.write("            <input type=\"submit\" value=\"로그인\" class=\"submit\" 	onclick=\"return loginCheck()\">\r\n");
      out.write("            <input type=\"button\" value=\"회원가입\" class=\"cancel\" onclick=\"location.href='bs.do?cmd=contract'\">\r\n");
      out.write("            <input type=\"button\" value=\"아이디 비밀번호 찾기\" class=\"submit\" onclick=\"find_account()\">     \r\n");
      out.write("    </div><br><br>\r\n");
      out.write("    <div>&nbsp;&nbsp;&nbsp;");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("</article>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"clear\"></div>\r\n");
      out.write("\r\n");
      out.write("	<footer>\r\n");
      out.write("		<hr>\r\n");
      out.write("		<div id=\"logo\">\r\n");
      out.write("			<a href=\"bs.do?cmd=index\"><img alt=\"\" src=\"images/footer/logo.png\" width=\"200px\"></a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"copy\">\r\n");
      out.write("			회사명 : (주)청년문고 | 대표이사 : ㅁㅁㅁ <br>\r\n");
      out.write("			소재지 : 서울시 서대문구 신촌로 141 <br>\r\n");
      out.write("			사업자 등록번호 : 000-00-00000 | 통신판매업 신고번호 : 2022-서울신촌-00000 [사업자정보확인] <br>\r\n");
      out.write("			개인정보관리 책임자 : ㅁㅁㅁ | E-mail : asdf@naver.com | 대량주문 : 02-000-0000 <br>\r\n");
      out.write("			COPYRIGHT@CHEONGNYEONBOOKSTORE INC.ALLRIGHTS RESERVED. <br>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"serviceimg\">\r\n");
      out.write("			<img alt=\"\" src=\"images/footer/customer_servicecenter.jpg\" width=\"100px\">\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
